version: "2"

services:
    mysql:
        build: ./mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - 33060:3306
        environment:
            MYSQL_DATABASE: dacs
            MYSQL_USER: dacs
            MYSQL_PASSWORD: dacs
            MYSQL_ROOT_PASSWORD: dacs
